# Numpy Practice - Answers

## Step 1
- import numpy, pandas, matplotlib, 
- Initialize a numpy array with the integers: 1, 2, 3, 4 - call it dat1
- Initialize a numpy array with the integers: 5, 6, 7, 8 - call it dat2

In [4]:
# Imports
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [5]:
# Define the arrays
dat1 = np.array([1, 2, 3, 4])
dat2 = np.array([5, 6, 7, 8])

## Step 2

- Combine dat1 & dat2 into a new array, with shape [2, 4]
- Call the new array dat3
- Print out the shape of the new array

In [6]:
# Stack the arrays, vertically
dat3 = np.vstack([dat1, dat2])

In [7]:
# Check the array shape
dat3.shape

(2, 4)

In [8]:
# Or, this is another way to get the shape
np.shape(dat3)

(2, 4)

## Step 3
- Find the average across the columns

In [8]:
# Use the np.mean function, specifying which axis to operate across
np.mean(dat3, axis=1)

array([ 2.5,  6.5])

In [25]:
# Alternatively, you can access 'mean' as a method available to the array object
dat3.mean(axis=1)

array([ 2.5,  6.5])

## Step 4
- Find all of the elements in 'dat3' that are divisible by three.
- Hint: your answer for this can / should be a boolean array

In [27]:
# Create a boolean array indicating whether each element is evenly divisible by 3
inds = dat3 % 3 == 0

## Step 5
- Use your answer from step 4 to extract the values from 'dat3'

In [30]:
# Index into 'dat3' with the boolean array
dat3[inds]

array([3, 6])